import random   

user_display_list = [
    "What are you looking for today?",
    "What can I help you with?",
    "What would you like to know?",
    "What do you need information on?",
    "What do you want to know?",
    "What would you like to learn?",
    "What do you need to know?",
    "What do you want to learn?",
    "How can I assist you today?",
    "Is there something specific you’re searching for?",
    "What topic are you interested in?",
    "What information do you need right now?",
    "How can I make your search easier?",
    "What are you curious about today?",
    "What question do you have in mind?",
    "What knowledge are you seeking?",
    "What would you like me to explain?",
    "Is there something I can clarify for you?",
    "What subject do you want to explore?",
    "What do you want to find out today?",
    "Can I help you with something in particular?",
    "What would you like to discuss?",
    "Is there a topic you’re interested in learning about?",
    "How can I guide you today?",
    "What kind of information are you looking for?",
    "What would make your day easier right now?",
    "Are you looking for answers to a question?",
    "What do you need help understanding?",
    "What are you hoping to discover?",
    "What would you like to get more info on?",
    "Can I assist with anything specific?",
    "What knowledge can I share with you?",
    "What would make your work or learning easier today?",
    "What question is on your mind?",
    "How can I support your search?",
    "What topic should we dive into?",
    "What would you like me to look up for you?",
    "Is there information you need urgently?",
    "What are you interested in figuring out?",
    "What can I explain for you today?",
    "What would you like clarity on?",
    "Do you have a question I can help with?",
    "What kind of help are you looking for?",
    "What subject do you want to understand better?",
    "What can I do to assist your learning?",
    "Are you searching for specific details?",
    "What do you need guidance on?",
    "What would you like to get answers about?",
    "How can I make your inquiry easier?",
    "What would you like to uncover today?",
]


def get_random_user_display():
    return random.choice(user_display_list)
